### ISSUE TITLE
Rust API documentation and samples

### ISSUE THREAD

**Issue by feribg** [Eventual-Inc/Daft#1828]
Would be great to expose the API spec and docs for rust, examples, examples on how to extend etc. Since python has plenty of tools to do the same job, but rust practically 0.

**Comment by jaychia** [comment]
Hi @feribg !

Thanks for making this issue -- we don't currently expose a Rust API because most of the interesting Daft functionality (distributed execution etc) is not currently exposed in Rust and takes place in Python still.

However, we do intend on making Daft much easier to extend and contribute to. Is this something that you would be interested in?

**Comment by feribg** [comment]
Gotcha thanks, I actually stumbled upon the project looking for a dask alternative in Rust, the only even remotely similar thing is balistra which also doesn't seem to expose a clean rust api to the scheduler.

**Comment by jaychia** [comment]
Makes sense! I'm not sure how difficult it would be, but most of Ray is written in C++ and could perhaps be easily binded to Rust for a Rust API.
