### ISSUE TITLE
[EXPRESSIONS] `.sqrt`

### ISSUE THREAD

**Issue by colin-ho** [Eventual-Inc/Daft#1918]
`sqrt()`

Compute the square root of the expression.

**Comment by chandbud5** [comment]
I did try it out, but I've been struggling to make progress on this issue, since I am not strong on rust. I think it would be better for someone else to take it on. Could you please unassign me from this issue? I appreciate the opportunity to contribute, and I look forward to picking up other issues that might be a better fit for my skills. Sorry for any inconvenience caused.

**Comment by colin-ho** [comment]
> I did try it out, but I've been struggling to make progress on this issue, since I am not strong on rust. I think it would be better for someone else to take it on. Could you please unassign me from this issue? I appreciate the opportunity to contribute, and I look forward to picking up other issues that might be a better fit for my skills. Sorry for any inconvenience caused.

No worries at all!

**Comment by dmaymay** [comment]
Hey @colin-ho , this seemed a tad easier than .clip() to start with so I wanted to give it a try, but I ran into a similar issue, I made a draft pull request on this to start with. 

This solution "works" but similarly, it returns the original type, losing precision in the output. I wrote another solution in the commented out code in array/ops/sqrt.rs but ran into the same issue as .clip() when running it.
