### ISSUE TITLE
[EXPRESSIONS] `.str.substr`

### ISSUE THREAD

**Issue by colin-ho** [Eventual-Inc/Daft#1934]
`substr(start, length=None)`

Computes the substr with a given starting index and length.

https://ibis-project.org/reference/expression-strings#ibis.expr.types.strings.StringValue.substr

**Comment by danila-b** [comment]
Hey! I assume this one is still needed. 
I would be happy to give it a try and contribute to it.

**Comment by samster25** [comment]
@danila-b go for it!

**Comment by danila-b** [comment]
Thanks @samster25 

I opened a draft PR with some initial blueprints. https://github.com/Eventual-Inc/Daft/pull/2269

There is a bit of confusion about data type mapping since `substr(start, len)` parameters can be of a different datatype at the same time. I could use some pointers or examples on how it can be handled elegantly. https://github.com/Eventual-Inc/Daft/pull/2269#discussion_r1597607896

**Comment by colin-ho** [comment]
Closes with https://github.com/Eventual-Inc/Daft/pull/2269
