### ISSUE TITLE
SQL Support within read_deltalake

### ISSUE THREAD

**Issue by Josh-Hiz** [Eventual-Inc/Daft#2463]
**Is your feature request related to a problem? Please describe.**
Whenever reading extremely large deltalake files from Azure, I want to be able to run a SQL query while reading, similar to duckdb, before the final dataframe is returned. I do not want to have the entire table always, and I am not sure why Daft doesnt support this.

**Describe the solution you'd like**
I want to be able to specify a sql string within ``read_deltalake``:

```python
df = daft.read_deltalake(delta_url, io_config=io_config, _multithreaded_io=True, query=query)
return df.to_pandas( )
```

I know that Daft has extensive SQL syntax support, including TSQL which intrigues me greatly and I, as long as probably many others would like the convenience of executing queries when reading.

**Describe alternatives you've considered**
I've tried combining duckdb in-memory querying with Daft deltalake reading, but I still need to convert daft dataframe to pandas to even be used with duckdb in the first place, which takes a long while.

In the meant time, is there any way in Daft to try replicating what I want for now?

**Comment by jaychia** [comment]
Hi @Josh-Hiz!

Thanks for the question. DeltaLake doesn't have it's on query engine (it's just a storage layer), so unlike our support for reading from SQL databases using `daft.read_sql(...)`, we aren't able to take in a SQL query since there's nothing to execute it on!

There are a few possible approaches here:

Use Daft Dataframe syntax to query your deltalake table (this is essentially "running a SQL query while reading", except that your query is defined as a Daft Dataframe)

```
df = daft.read_deltalake(...)

# Your query here
df = df.where(df["x"] == 1)
df = df.with_column("x", df["x"] + 1)

df.to_pandas()
```

Alternatively, if SQL is a hard requirement for you, you will need a query engine that understands SQL. (Daft today does not yet support building our queries using SQL, only our dataframe API!). If your query engine of choice is DuckDB, you can interoperate this with Daft by using Arrow as an intermediate dataframe format:

```
# Warning: I'm not familiar with DuckDB syntax!
data = duckdb.sql(...).to_arrow()

df = daft.from_arrow(data)
...
```


We are looking at adding SQL support in the coming few months! That is to say, we want to make something like the following possible:

```
df = daft.read_deltalake(...)

df = daft.sql(f"""
SELECT x + 1 FROM {df} WHERE x == 1
""")

df.to_pandas()
```

This is not yet available today though!

**Comment by Josh-Hiz** [comment]
Hi @jaychia I appreciate your response, the snippet you provided:

```python
df = daft.read_deltalake(...)

df = daft.sql(f"""
SELECT x + 1 FROM {df} WHERE x == 1
""")

df.to_pandas()
```

Is more or less exactly what I had in mind, it would be a wonderful addition for those (like myself) that need SQL as a hard requirement. The main issue with duckdb when querying is it will create temp folders that (when going on very large deltalakes) can be up to 100's of gigabytes in size, obviously that isn't optimal and queries would need to be reduced in scale. Daft's speed and its ability to scale though hopefully can handle this.

**Comment by jaychia** [comment]
Closing this issue in favor of #2468
