### ISSUE TITLE
Materialized partitions are not being properly deleted, leading to OOM

### ISSUE THREAD

**Issue by sagiahrac** [Eventual-Inc/Daft#2810]
**Describe the bug**
When iterating through the dataset using pyrunner, reading tasks are being executed across multiple threads. We wait on the thread pool until the first thread completes. However, if not all threads have finished execution before returning from the wait, the remaining threads may not be properly collected or cleaned up after they finish. This behavior can eventually cause an OOM.

**To Reproduce**
It only reproduces with the `sample` operation after reading the dataset.
```python
if not os.path.exists("dummy_data"):
    df = daft.from_pydict({"x": np.random.random(1_000_000_000)}).repartition(100)
    df.write_parquet("dummy_data")

while True:
    df = daft.read_parquet("dummy_data").sample(fraction=0.9)
    x = next(iter(df))
```
The inflight tasks dict will keep growing until we reach OOM.

**Expected behavior**
When garbage collector collects a dataframe, all of its related tasks will be collected as well (i.e. using `DataFrame.__del__`).

**Additional context**
```
python 3.11.9
daft 0.3.2
pyarrow 16.1.0
```

**Comment by jaychia** [comment]
Ah good find, we'll take a look

**Comment by jaychia** [comment]
I have a potential fix in https://github.com/Eventual-Inc/Daft/pull/2812 

I was able to verify that it correctly cleans up the "orphaned" tasks and futures from GC'ed generators in your provided example

However I wasn't able to reproduce the OOM error, likely because I haven't run the workload on enough iterations 😛 so I can't definitely say if this PR fixes the issue. Any chance if you could try it out on your end? I can push a nightly for you to try out!

**Comment by sagiahrac** [comment]
Great job on the fix! The inflight tasks are now being cleared when the garbage collector processes the dataframe. Thanks!
