### ISSUE TITLE
Azure storage account not properly set for Unity Catalog

### ISSUE THREAD

**Issue by kevinzwang** [Eventual-Inc/Daft#3142]
### Describe the bug

See conversation here: https://github.com/Eventual-Inc/Daft/issues/2903#issuecomment-2434385035

### To Reproduce

```python
>>> unity = UnityCatalog(endpoint=DATABRICKS_HOST,token=PAT_TOKEN_AZURE)
>>> unity_table_ext = unity.load_table("some_catalog.some_schema.some_table") 
>>> df_ext = daft.read_deltalake(unity_table_ext)
>>> df_ext.show()

DaftCoreException: DaftError::External Generic AzureBlob error: Azure Storage Account not set and is required.
 Set either `AzureConfig.storage_account` or the `AZURE_STORAGE_ACCOUNT` environment variable.
```

### Expected behavior

Daft sets Azure storage account and properly shows dataframe

### Component(s)

Other

**Comment by djouallah** [comment]
same error here

**Comment by kevinzwang** [comment]
Hi @anilmenon14, thanks for the help! what would a table URI look like for Azure and what part would be the storage account?

**Comment by anilmenon14** [comment]
Hi @kevinzwang , for ADLS Gen2 , it looks like the below example:

abfss://<some_container>@**<storage_account>**.dfs.core.windows.net/<directory>
Where the **<storage_account>** is what we are interested in extracting.

One thing to consider is that Azure storage could also be on ADLS Gen1 (`adl://` protocol) or Blob storage (`wasbs://`) . However, I did some checking and we should be safe to assume `abfss://` URI's for Databricks Unity Catalog since Unity catalog has a pre-requisite for ADLS Gen2 atleast. 
**Source**: [documentation from Databricks published blog](https://www.databricks.com/blog/migrating-tables-hive-metastore-unity-catalog-metastore)

**Comment by kevinzwang** [comment]
Gotcha. Thank you @anilmenon14 for the information! In that case, it looks like something we probably would like to fix on the rust side in the Azure code, so automatic storage account detection could actually be enabled for any Azure read and not just unity. Feel free to take a stab at that, otherwise I will work on it tomorrow

**Comment by anilmenon14** [comment]
Thanks @kevinzwang . I suppose you mean that it is best to have changes applied in `src/daft-io/src/azure_blob.rs` in around [this section](https://github.com/Eventual-Inc/Daft/blob/f966e02e3aeea2a2ac42bec3c087e49995117d6c/src/daft-io/src/azure_blob.rs#L147-L154) to handle this.
I am a complete beginner level in Rust, so haven't figured out how to get that done and would be interested to see and learn.
Since `table_uri` is an object on `daft.unity_catalog.unity_catalog.UnityCatalogTable` and not part of the `IOConfig`, I am curious to learn how that can be handled on the Rust side.

**Comment by kevinzwang** [comment]
No worries @anilmenon14 I'll get a PR out for this, if you could test it out that would be very helpful already!

**Comment by anilmenon14** [comment]
Absolutely @kevinzwang  . Happy to help get the testing done.

**Comment by kevinzwang** [comment]
@djouallah @g-kannan The fix for the Unity Azure storage account issue has been merged into our main branch and will be in our next release! Feel free to reopen the issue if you encounter a problem with the fix

**Comment by g-kannan** [comment]
Hi Kevin, 

Sorry, i'm facing the same error in  0.3.13 as well. Anything to change in code?

Code:
io_config = IOConfig(azure=AzureConfig(storage_account="storageaccount"))
df = daft.read_deltalake(table=unity_table_ext,io_config=io_config)

Error:
DaftCoreException: DaftError::External Generic AzureBlob error: Azure Storage Account not set and is required.
 Set either `AzureConfig.storage_account` or the `AZURE_STORAGE_ACCOUNT` environment variable.

**Comment by g-kannan** [comment]
Hi Kevin, 

Noted this in latest release as well and not working

![image](https://github.com/user-attachments/assets/dd36f90b-3254-41ff-aaa9-ff5033635990)

**Comment by anilmenon14** [comment]
Hey @g-kannan , 

@kevinzwang has included a new feature in 3.10.0 that has made the API much simpler and intuitive , for Azure users, from that version onwards.
The PR where the feature was included is [[FEAT] Infer Azure storage account from uri](https://github.com/Eventual-Inc/Daft/pull/3165)

```
import daft 
import os
from daft.unity_catalog import UnityCatalog

# Pre-req: Include the below env vars in your runtime
DATABRICKS_HOST = os.environ.get('DATABRICKS_HOST') 
PAT_TOKEN = os.environ.get('PAT_TOKEN') 

unity = UnityCatalog(endpoint=DATABRICKS_HOST,token=PAT_TOKEN)
unity_table_ext = unity.load_table("some_catalog_in_uc.some_schema_in_uc.some_table_in_uc")
df_ext = daft.read_deltalake(unity_table_ext)
df_ext.show()

```

I tried the above on 3.13.0 and it works well. Let me know what you see.

**Comment by kevinzwang** [comment]
Hi @g-kannan , as @anilmenon14 said, Daft should now automatically retrieve the correct storage account from your UC table. Also, if you pass in a unity table and it has credentials attached to it, `read_deltalake` will ignore the `io_config` parameter. 

However, passing in an io_config should not break the existing one. I have a few suspicions about what the cause of this is. Could you print out `unity_table_ext.table_uri`? Daft can derive the storage account from a URL that is in the form `abfss://<some_container>@<storage_account>.dfs.core.windows.net/`, curious to see what yours looks like

**Comment by g-kannan** [comment]
Hi Anil\Kevin, Thanks for this. I think its a env issue with my Gitpod workspace. I deleted and retried in new where it worked as it should. table_uri also shows as mentioned above. 

<img width="425" alt="image" src="https://github.com/user-attachments/assets/ed09ea58-b54b-4ef4-ac14-878d2ba05923">

**Comment by kevinzwang** [comment]
Great! Glad to hear
