### ISSUE TITLE
UDF Type Inference

### ISSUE THREAD

**Issue by Lundez** [Eventual-Inc/Daft#3549]
### Is your feature request related to a problem?

Building UDF's is a lot of code that should be possible to automate to make Deep Learning pipelines simpler. In a Data Engineering Pipeline I see specifying types to something "exact" makes a lot of sense. But for Deep Learning you're "fine" with a more crude typing as you usually cast it at the end anyways.

### Describe the solution you'd like

I see multiple ways to select dtype from a UDF

1. Specifiy `return_dtype` as is now, but also through Python types (`int`, `str`, ...) and potentially Strings (`"string"`) and SQL String Type.
2. Don't specify `return_dtype` and `Daft` infers the type by first non-null return value (this is how Polars does it).

### Additional Context

This would help ML Engineers build great pipelines to take training data from S3, transform/augment, and into a model to train/infer.

I think cleaning the code up by "inferred-dtype" would help plenty of users to adopt this.

I'm happy to help you with implementation, but I'd need guidance on how to do this best.

### Would you like to implement a fix?

No

**Comment by andrewgazelka** [comment]
Thanks for the suggestion. @kevinzwang do you have any thoughts on this?

**Comment by Lundez** [comment]
@andrewgazelka connects with #3547

**Comment by andrewgazelka** [comment]
@jaychia

**Comment by kevinzwang** [comment]
Hi @Lundez, thank you for bringing this up. I think it makes sense to be able to map Python data types to Daft ones, and as Jay mentioned, should not be too difficult to do. 

On the other hand, I do not anticipate that we will do type inference similar to Polars, since the only ways to do this are:
1. defer schema resolution to runtime, which Polars can do because resource accounting is not significantly useful for a local engine, but to Daft, as a distributed engine, knowing the size of the data is pretty important
3. run a sample query to determine the output type of a UDF, but this is not necessary easy/performant to do since we would need to do this for every UDF and ensure that the output of each query is not empty. plus it adds a level of non-determinism to the execution of the UDF which may not be appreciated by users

The Python typing is a good idea though, @Lundez actually would you be interested in contributing it? I'd be happy to guide you.

**Comment by Lundez** [comment]
@kevinzwang yeah, I forgot about the distributed part of the engine 🙈 
Perhaps it could be a mode for the native local engine (swordfish), and if we run on Ray it throws error?

But yeah, simply Python typing would be helpful 👍

**Comment by kevinzwang** [comment]
It could theoretically be done for Swordfish but I'm hesitant to let the APIs for the two engines diverge. Better to be strict about it so that a user can transparently switch between execution modes as much as possible.

**Comment by Lundez** [comment]
> It could theoretically be done for Swordfish but I'm hesitant to let the APIs for the two engines diverge. Better to be strict about it so that a user can transparently switch between execution modes as much as possible.

Sound reasoning!

**Comment by jaychia** [comment]
Added a quick PR that adds functionality for inference from Python types -- we could also add a follow-on that will add functionality to parse SQL-compatible strings I think!
