### ISSUE TITLE
ExpressionTypeError: Unable to resolve type for operation: if_else

### ISSUE THREAD

**Issue by xdssio** [Eventual-Inc/Daft#519]
Unclear if that is a bug, a feature idea, or a communication need.

# Issue
What should be done if we use if_else and set values of a different type?

**To Reproduce**
Use an if_else with different types.
I set a float as a missing value for an int column in this example.

```python
import daft

df = daft.DataFrame.from_pydict({'a':[1,None,3]})
df.with_column('b', df['a'].is_null().if_else(0.0, df['a'])).show()
```

**Expected behaviour**
Intuitively, I would expect it to cast to int, but not sure how that would be implemented in the average case.    
Maybe for a native *fill_na*, we can apply an automatic cast, but on the original *if_else*, we should keep it as an error.

**Comment by jaychia** [comment]
Thanks @xdssio! 

The behavior here is correct because, for example, if we do an `.if_else(float, string)`, the behavior is not well defined. In the above case you presented, we would suggest: `df['a'].is_null().if_else(0.0, df['a'].cast(float)))`.

I agree that perhaps the error message here should be more explicit. We should inform the user that the types of the columns provided to `if_else` need to be the same.

**Comment by jaychia** [comment]
This is handled by supertype promotion semantics in our new Rust execution engine!
