### ISSUE TITLE
[Rust] Propagate Ctrl-C interrupts from Python to Rust

### ISSUE THREAD

**Issue by xcharleslin** [Eventual-Inc/Daft#755]
Currently, if Daft is executing a kernel in Rust, Ctrl-C will not interrupt it - it will only be interrupted after execution is handed back to Python. This is particularly an issue if the kernel is taking a long time to run, because then Daft appears uninterruptible.

**Comment by jaychia** [comment]
https://pyo3.rs/main/faq#ctrl-c-doesnt-do-anything-while-my-rust-code-is-executing

Interesting - apparently Rust suggests that we should check with the Python interpreter at regular intervals.

**Comment by vishwanath1306** [comment]
Yes, you can use the `check_signals` function inside the loop to check for any SIGINT periodically. 

https://docs.rs/pyo3/latest/pyo3/marker/struct.Python.html#method.check_signals

**Comment by jaychia** [comment]
Thanks @vishwanath1306 !

We actually will probably want to avoid the overhead of any SIGINT checking loops. Instead, a good approach might just be to speed up our kernels so that we can return control quicker over to Python, and have Python do the signal handling!

For instance, since we sped up our join kernels on `rust-main` this has been much more of a non-issue :)

I'll close this issue for now until we need to revisit it!
